// Persian translations for Fortnite cosmetic item names
export const PERSIAN_NAMES: Record<string, string> = {
  // ===== OUTFITS / پوشاک =====
  // Default / پیش‌فرض
  "Jonesy": "جونزی",
  "Ramirez": "رامیرز",
  "Hawk": "هاوک",
  "Headhunter": "شکارچی سر",
  "Recon Expert": "کارشناس شناسایی",
  "Aerial Assault Trooper": "سرباز هوایی",
  "Renegade Raider": "غارتگر یاغی",
  "Survival Specialist": "متخصص بقا",
  "Commando": "کماندو",

  // Season 1-3 classics
  "Skull Trooper": "سرباز جمجمه",
  "Ghoul Trooper": "سرباز غول",
  "Black Knight": "شوالیه سیاه",
  "Red Knight": "شوالیه قرمز",
  "Blue Squire": "سرباز آبی",
  "Royale Knight": "شوالیه سلطنتی",
  "Sparkle Specialist": "متخصص درخشش",
  "Brite Bomber": "بمب‌انداز درخشان",
  "Cuddle Team Leader": "رهبر تیم عشقی",
  "Love Ranger": "رنجر عشق",
  "Rabbit Raider": "مهاجم خرگوش",
  "Crackshot": "تیرانداز ماهر",
  "Nog Ops": "عملیات ناگ",
  "Ginger Gunner": "تفنگدار زنجبیلی",
  "Ice King": "پادشاه یخ",
  "Ice Queen": "ملکه یخ",

  // Season 4-5
  "Carbide": "کاربید",
  "Omega": "امگا",
  "Drift": "دریفت",
  "Ragnarok": "راگناروک",
  "Calamity": "فاجعه",
  "Dire": "هیولا",
  "Valkyrie": "والکیری",
  "Road Trip": "سفر جاده‌ای",
  "Bullseye": "هدف دقیق",
  "Lynx": "سیاه‌گوش",
  "Kitsune": "کیتسونه",
  "Tomatohead": "سر گوجه‌ای",
  "Tomatoe Head": "سر گوجه‌ای",
  "Rex": "رکس",
  "Dino Guard": "نگهبان دایناسور",

  // Season 6-9
  "Peely": "پیلی",
  "Peely Bone": "پیلی اسکلتی",
  "Agent Peely": "عامل پیلی",
  "Eternal Voyager": "سیاح ابدی",
  "Dusk": "غروب",
  "Gale Force": "نیروی باد",
  "Vendetta": "انتقام",
  "Enforcer": "مجری",
  "Predator": "شکارچی",
  "Omen": "فال بد",
  "Nite Nite": "شب شب",
  "Shriek": "جیغ",
  "Hay Man": "مرد پوشال",
  "Season X": "فصل X",

  // Chapter 2
  "Midas": "میداس",
  "Jules": "ژول",
  "Brutus": "بروتوس",
  "TNTina": "تی‌ان‌تینا",
  "Meowscles": "عضله‌گربه",
  "Kit": "کیت",
  "The Mandalorian": "ماندالوریایی",
  "Boba Fett": "بوبا فت",
  "Grogu": "گروگو",
  "Mave": "ماو",
  "Turk": "تورک",
  "Chaos Agent": "عامل آشوب",
  "Doctor Slone": "دکتر اسلون",
  "The Foundation": "بنیاد",
  "The Foundation (Reforged)": "بنیاد (بازسازی‌شده)",
  "IO Guard": "نگهبان IO",
  "The Imagined": "تخیل‌شده",
  "The Origin": "خاستگاه",
  "The Last": "آخرین",
  "The Visitor": "بازدیدکننده",
  "The Scientist": "دانشمند",
  "Dark Voyager": "سیاح تاریک",
  "Exalted Ice King": "پادشاه یخ متعالی",
  "Elite Jules": "ژول الیت",

  // Chapter 3-7
  "Shanta": "شانتا",
  "Cube Queen": "ملکه مکعب",
  "Cube Assassin": "قاتل مکعب",
  "Geno": "ژنو",
  "The Imagined Order": "نظم تخیلی",
  "Gunnar": "گونار",
  "Huntmaster Saber": "شکارچی ارشد",
  "Rift Warden Stellan": "نگهبان شکاف",
  "Snap": "اسنپ",
  "Imperial Stormtrooper": "طوفان‌تروپر امپراتوری",
  "Luke Skywalker": "لوک اسکای‌واکر",
  "Darth Vader": "دارت ویدر",
  "Han Solo": "هان سولو",
  "Leia Organa": "لیا اورگانا",
  "Rey": "ری",
  "Kylo Ren": "کایلو رن",
  "Fennec Shand": "فنک شند",
  "Ahsoka Tano": "اهسوکا تانو",
  "Chewbacca": "چووباکا",

  // Marvel / DC
  "Iron Man": "مرد آهنی",
  "Thor": "ثور",
  "Captain America": "کاپیتان آمریکا",
  "Black Widow": "بیوه سیاه",
  "Black Panther": "پلنگ سیاه",
  "Groot": "گروت",
  "Star-Lord": "استار-لرد",
  "Gamora": "گامورا",
  "Spider-Man": "مرد عنکبوتی",
  "Wolverine": "ولورین",
  "Storm": "طوفان",
  "Jean Grey": "ژان گری",
  "Mystique": "رمزآلود",
  "She-Hulk": "هالک زن",
  "Doctor Strange": "دکتر استرنج",
  "Batman": "بتمن",
  "Superman": "سوپرمن",
  "Harley Quinn": "هارلی کوین",
  "Catwoman": "زن گربه‌ای",
  "Aquaman": "آکوامن",
  "Deathstroke": "دث‌استروک",
  "Green Arrow": "تیر سبز",

  // Gaming Legends
  "Master Chief": "رئیس ارشد",
  "Kratos": "کراتوس",
  "Aloy": "الوی",
  "Lara Croft": "لارا کرافت",
  "Geralt of Rivia": "گرالت از ریویا",
  "Ezio Auditore": "اتزیو",
  "Jinx": "جینکس",
  "Vi": "وی",
  "Horizon": "هورایزن",

  // Icon Series (celebrities)
  "Ariana Grande": "آریانا گرانده",
  "Travis Scott": "تراویس اسکات",
  "Marshmello": "مارشملو",
  "Ninja": "نینجا",
  "Loserfruit": "لوزرفروت",
  "Bugha": "بوگا",
  "LeBron James": "لبرون جیمز",
  "Neymar Jr": "نیمار",
  "Naruto Uzumaki": "ناروتو",
  "Sasuke Uchiha": "ساسوکه",
  "Sakura Haruno": "ساکورا",
  "Kakashi Hatake": "کاکاشی",
  "Itachi Uchiha": "ایتاچی",
  "Rock Lee": "راک لی",
  "Rick Sanchez": "ریک سانچز",
  "Morty Smith": "مورتی اسمیت",
  "Peter Griffin": "پیتر گریفین",

  // ===== EMOTES / احساسات =====
  "Floss": "فلاس",
  "Orange Justice": "عدالت نارنجی",
  "Take the L": "ببر L را",
  "Ride the Pony": "سواری بر اسب",
  "Fresh": "تازه",
  "Running Man": "مرد دونده",
  "Best Mates": "بهترین دوستان",
  "Worm": "کرم",
  "Electro Shuffle": "شافل الکتریکی",
  "Groove Jam": "گروو جم",
  "Robot": "ربات",
  "Scenario": "سناریو",
  "Phone It In": "زنگ بزن",
  "Rollie": "رولی",
  "Toosie Slide": "لیز توسی",
  "Savage": "وحشی",
  "Hype": "هایپ",
  "Dab": "دب",
  "Infinite Dab": "دب بی‌نهایت",
  "Default Dance": "رقص پیش‌فرض",
  "Twist": "تویست",
  "Flare": "شعله",
  "Accolades": "تحسین",
  "Star Power": "قدرت ستاره",
  "Turk's Victory": "پیروزی ترکی",
  "Gangnam Style": "گانگنام استایل",
  "Llama Bell": "زنگ لاما",
  "Rocket Rodeo": "رودئو راکت",
  "Victory Lap": "دور پیروزی",
  "Shimmer Slide": "لیز درخشان",
  "Butter Barn": "انبار کره",
  "Fortnite Shuffle": "فورتنایت شافل",

  // ===== PICKAXES / کلنگ =====
  "Default Pickaxe": "کلنگ پیش‌فرض",
  "Raider's Revenge": "انتقام غارتگر",
  "Candy Axe": "تبر شیرینی",
  "Reaper": "داسدار",
  "Studded Axe": "تبر میخدار",
  "Driver": "گلف‌باز",
  "Dual Edge": "لبه دوگانه",
  "Plunja": "پلانجا",
  "Minty Pickaxe": "کلنگ نعنایی",
  "Power Chord": "آکورد قدرت",
  "Axeroni": "اکسرونی",
  "Star Wand": "عصای ستاره",
  "Disco Brawl": "دعوای دیسکو",
  "Rainbow Smash": "له‌کردن رنگین‌کمان",
  "Batsickle": "داس خفاش",
  "Choppa": "چاپا",
  "Lazer Chomp": "گاز لیزری",
  "Eon Blade": "تیغه ابدی",
  "Mjolnir Strike": "ضربه میولنیر",
  "Stormbreaker": "شکننده طوفان",
  "Black Panther's Vibranium Claws": "چنگال‌های ویبرانیوم",

  // ===== GLIDERS / چتر =====
  "Mako": "ماکو",
  "Aerial Assault One": "تهاجم هوایی یک",
  "Royale Air": "هوای سلطنتی",
  "Pivot": "محور",
  "Airhead": "سر هوایی",
  "Blue Streak": "خط آبی",
  "Gold King": "پادشاه طلایی",
  "Cruiser": "کروزر",
  "Coaxial Copter": "هلیکوپتر محوری",
  "Shrieking Shield": "سپر جیغ",
  "Millennium Falcon": "عقاب هزاره",
  "X-Wing": "بال X",
  "TIE Fighter": "جنگنده TIE",

  // ===== WRAPS / پوشش سلاح =====
  "Dragon Scales": "فلس اژدها",
  "Tiger": "ببر",
  "Camo": "کمو",
  "Iridescent": "درخشان",
  "Lazerbeam": "پرتو لیزر",
  "Arctic Camo": "کمو قطبی",
  "Desert Storm": "طوفان صحرا",
  "Checkered": "شطرنجی",
  "Rose Gold": "طلای رزی",
  "No Sweat": "بدون عرق",
  "Wild Agent": "عامل وحشی",
  "Bananas": "موز",
  "Melty": "آب‌شده",

  // ===== BACKPACKS / کوله‌پشتی =====
  "Bone Wings": "بال‌های استخوانی",
  "Glitch": "گلیچ",
  "Hamirez": "هامیرز",
  "Dark Wings": "بال‌های تاریک",
  "Rainbow Clover": "شبدر رنگین‌کمان",
  "Neo Phrenzy": "دیوانگی نئو",
  "Xander": "زاندر",
  "Astral Axe": "تبر آسمانی",

  // ===== BUNDLES / بسته‌ها =====
  "Starter Pack": "بسته مبتدی",
  "Double Helix": "مارپیچ دوگانه",
  "Deep Space Lander": "فرودگر فضای عمیق",
  "Honor Guard": "گارد افتخار",
  "Galaxy": "کهکشان",
  "Ikonik": "آیکونیک",
  "Royale Bomber": "بمب‌انداز سلطنتی",

  // ===== SPRAYS / اسپری =====
  "Victory": "پیروزی",
  "GG": "GG",
  "Skull": "جمجمه",
  "Fire": "آتش",
  "Sparkle": "درخشش",
};

export function getItemNameFa(nameEn: string): string {
  // Direct match
  if (PERSIAN_NAMES[nameEn]) return PERSIAN_NAMES[nameEn];

  // Try partial match for bundle variations
  for (const [key, val] of Object.entries(PERSIAN_NAMES)) {
    if (nameEn.toLowerCase().includes(key.toLowerCase()) && key.length > 4) {
      return val;
    }
  }

  return nameEn; // fallback to English
}
