import { Quest } from "@/types";

export const QUESTS: Quest[] = [
  // ===== DAILY QUESTS =====
  {
    id: "daily-001",
    titleFa: "آسیب با تفنگ تهاجمی",
    titleEn: "Deal Assault Rifle Damage",
    descriptionFa: "با استفاده از تفنگ تهاجمی به دشمنان آسیب بزنید",
    category: "daily",
    xpReward: 1000,
    target: 500,
    targetUnit: "آسیب",
    tags: ["combat", "rifle", "damage"],
  },
  {
    id: "daily-002",
    titleFa: "آسیب با شاتگان",
    titleEn: "Deal Shotgun Damage",
    descriptionFa: "با استفاده از شاتگان به دشمنان آسیب بزنید",
    category: "daily",
    xpReward: 1000,
    target: 200,
    targetUnit: "آسیب",
    tags: ["combat", "shotgun", "damage"],
  },
  {
    id: "daily-003",
    titleFa: "باز کردن صندوق‌ها",
    titleEn: "Open Chests",
    descriptionFa: "صندوق‌ها را در هر جایی باز کنید",
    category: "daily",
    xpReward: 1000,
    target: 3,
    targetUnit: "صندوق",
    tags: ["looting", "chests"],
  },
  {
    id: "daily-004",
    titleFa: "حذف دشمنان",
    titleEn: "Eliminate Opponents",
    descriptionFa: "دشمنان را حذف کنید",
    category: "daily",
    xpReward: 1000,
    target: 1,
    targetUnit: "حذف",
    tags: ["combat", "eliminate"],
  },
  {
    id: "daily-005",
    titleFa: "احیای همتیمی",
    titleEn: "Revive Teammates",
    descriptionFa: "همتیمی‌های خود را احیا کنید",
    category: "daily",
    xpReward: 1000,
    target: 2,
    targetUnit: "احیا",
    tags: ["teamwork", "revive"],
  },
  {
    id: "daily-006",
    titleFa: "مسافت طی‌شده پیاده",
    titleEn: "Travel Distance on Foot",
    descriptionFa: "با پای خود مسافت طی کنید",
    category: "daily",
    xpReward: 1000,
    target: 1000,
    targetUnit: "متر",
    tags: ["movement", "travel"],
  },
  {
    id: "daily-007",
    titleFa: "باز کردن جعبه مهمات",
    titleEn: "Search Ammo Boxes",
    descriptionFa: "جعبه‌های مهمات را جستجو کنید",
    category: "daily",
    xpReward: 1000,
    target: 3,
    targetUnit: "جعبه",
    tags: ["looting", "ammo"],
  },
  {
    id: "daily-008",
    titleFa: "تخریب سازه‌ها",
    titleEn: "Destroy Structures",
    descriptionFa: "سازه‌ها را تخریب کنید",
    category: "daily",
    xpReward: 1000,
    target: 2000,
    targetUnit: "آسیب",
    tags: ["building", "destroy"],
  },
  {
    id: "daily-009",
    titleFa: "آسیب با سلاح انفجاری",
    titleEn: "Deal Explosive Weapon Damage",
    descriptionFa: "با سلاح‌های انفجاری به دشمنان آسیب بزنید",
    category: "daily",
    xpReward: 1000,
    target: 200,
    targetUnit: "آسیب",
    tags: ["combat", "explosive", "damage"],
  },
  {
    id: "daily-010",
    titleFa: "جمع‌آوری محلول سپر",
    titleEn: "Collect Shield Potions",
    descriptionFa: "محلول‌های سپر را جمع‌آوری کنید",
    category: "daily",
    xpReward: 1000,
    target: 2,
    targetUnit: "محلول",
    tags: ["healing", "shield"],
  },
  {
    id: "daily-011",
    titleFa: "باز کردن Supply Drop",
    titleEn: "Open Supply Drops",
    descriptionFa: "Supply Drop‌ها را باز کنید",
    category: "daily",
    xpReward: 1000,
    target: 1,
    targetUnit: "Supply Drop",
    tags: ["looting", "supply"],
  },
  {
    id: "daily-012",
    titleFa: "آسیب با SMG",
    titleEn: "Deal SMG Damage",
    descriptionFa: "با استفاده از SMG به دشمنان آسیب بزنید",
    category: "daily",
    xpReward: 1000,
    target: 500,
    targetUnit: "آسیب",
    tags: ["combat", "smg", "damage"],
  },
  {
    id: "daily-013",
    titleFa: "بازماندن از دشمنان",
    titleEn: "Outlast Opponents",
    descriptionFa: "از تعداد بیشتری از دشمنان بیشتر بمانید",
    category: "daily",
    xpReward: 1000,
    target: 100,
    targetUnit: "بازیکن",
    tags: ["survival", "outlast"],
  },
  {
    id: "daily-014",
    titleFa: "جمع‌آوری کیت درمانی",
    titleEn: "Collect Medkits",
    descriptionFa: "کیت‌های درمانی را جمع‌آوری کنید",
    category: "daily",
    xpReward: 1000,
    target: 2,
    targetUnit: "کیت",
    tags: ["healing", "medkit"],
  },
  {
    id: "daily-015",
    titleFa: "آسیب با تک‌تیرانداز",
    titleEn: "Deal Sniper Rifle Damage",
    descriptionFa: "با تفنگ تک‌تیراندازی به دشمنان آسیب بزنید",
    category: "daily",
    xpReward: 1000,
    target: 300,
    targetUnit: "آسیب",
    tags: ["combat", "sniper", "damage"],
  },

  // ===== WEEKLY QUESTS - WEEK 1 =====
  {
    id: "week1-001",
    titleFa: "آسیب در Painted Palms یا Latte Landing",
    titleEn: "Damage Players at Painted Palms or Latte Landing",
    descriptionFa: "به بازیکنان در Painted Palms یا Latte Landing آسیب بزنید تا محیط امنیتی پادشاهی یخ را تأمین کنید",
    category: "weekly",
    xpReward: 20000,
    target: 500,
    targetUnit: "آسیب",
    week: 1,
    season: "chapter7-season2",
    tags: ["combat", "damage", "location"],
    isNew: false,
  },
  {
    id: "week1-002",
    titleFa: "باز کردن صندوق در Rebel Rock Ridge یا Fossil Falls",
    titleEn: "Search Chests at Rebel Rock Ridge or Fossil Falls",
    descriptionFa: "صندوق‌ها را در Rebel Rock Ridge یا Fossil Falls جستجو کنید",
    category: "weekly",
    xpReward: 20000,
    target: 7,
    targetUnit: "صندوق",
    week: 1,
    season: "chapter7-season2",
    tags: ["looting", "chests", "location"],
    isNew: false,
  },
  {
    id: "week1-003",
    titleFa: "تخریب سازه در Command Cavern",
    titleEn: "Destroy Structures at Command Cavern",
    descriptionFa: "سازه‌ها را در Command Cavern تخریب کنید",
    category: "weekly",
    xpReward: 20000,
    target: 200,
    targetUnit: "آسیب",
    week: 1,
    season: "chapter7-season2",
    tags: ["building", "destroy", "location"],
    isNew: false,
  },
  {
    id: "week1-004",
    titleFa: "جمع‌آوری زره در مکان‌های نام‌دار",
    titleEn: "Collect Armor in Named Locations",
    descriptionFa: "زره را در مکان‌های نام‌گذاری شده جمع‌آوری کنید",
    category: "weekly",
    xpReward: 20000,
    target: 3,
    targetUnit: "زره",
    week: 1,
    season: "chapter7-season2",
    tags: ["looting", "armor", "location"],
    isNew: false,
  },
  {
    id: "week1-005",
    titleFa: "حذف با شاتگان",
    titleEn: "Eliminate Players Using Shotguns",
    descriptionFa: "بازیکنان را با استفاده از شاتگان حذف کنید",
    category: "weekly",
    xpReward: 20000,
    target: 3,
    targetUnit: "حذف",
    week: 1,
    season: "chapter7-season2",
    tags: ["combat", "shotgun", "eliminate"],
    isNew: false,
  },

  // WEEK 2
  {
    id: "week2-001",
    titleFa: "شکست Dread Punisher Squibbly",
    titleEn: "Defeat Dread Punisher Squibbly",
    descriptionFa: "Dread Punisher Squibbly را شکست دهید تا درباره Chef Squibbly اطلاعات کسب کنید",
    category: "weekly",
    xpReward: 20000,
    target: 1,
    targetUnit: "مبارزه",
    week: 2,
    season: "chapter7-season2",
    tags: ["boss", "eliminate", "story"],
    isNew: false,
  },
  {
    id: "week2-002",
    titleFa: "حذف در مکان‌های نام‌دار",
    titleEn: "Eliminate Players at Named Locations",
    descriptionFa: "بازیکنان را در مکان‌های نام‌گذاری شده حذف کنید",
    category: "weekly",
    xpReward: 20000,
    target: 5,
    targetUnit: "حذف",
    week: 2,
    season: "chapter7-season2",
    tags: ["combat", "eliminate", "location"],
    isNew: false,
  },
  {
    id: "week2-003",
    titleFa: "جمع‌آوری محلول سپر در منطقه Polar Peak",
    titleEn: "Collect Shield Potions in Polar Peak Area",
    descriptionFa: "محلول‌های سپر را در منطقه Polar Peak جمع‌آوری کنید",
    category: "weekly",
    xpReward: 20000,
    target: 3,
    targetUnit: "محلول",
    week: 2,
    season: "chapter7-season2",
    tags: ["healing", "shield", "location"],
    isNew: false,
  },
  {
    id: "week2-004",
    titleFa: "آسیب با SMG",
    titleEn: "Damage Opponents with SMGs",
    descriptionFa: "با استفاده از SMG به دشمنان آسیب بزنید",
    category: "weekly",
    xpReward: 20000,
    target: 500,
    targetUnit: "آسیب",
    week: 2,
    season: "chapter7-season2",
    tags: ["combat", "smg", "damage"],
    isNew: false,
  },
  {
    id: "week2-005",
    titleFa: "باز کردن صندوق در غارها",
    titleEn: "Open Chests in Caves",
    descriptionFa: "صندوق‌ها را در غارها باز کنید",
    category: "weekly",
    xpReward: 20000,
    target: 3,
    targetUnit: "صندوق",
    week: 2,
    season: "chapter7-season2",
    tags: ["looting", "chests", "cave"],
    isNew: false,
  },

  // WEEK 3
  {
    id: "week3-001",
    titleFa: "جمع‌آوری مکعب‌های آشوب",
    titleEn: "Collect Chaos Cubes",
    descriptionFa: "مکعب‌های آشوب را در سراسر نقشه جمع‌آوری کنید",
    category: "weekly",
    xpReward: 20000,
    target: 5,
    targetUnit: "مکعب",
    week: 3,
    season: "chapter7-season2",
    tags: ["collect", "chaos", "cube"],
    isNew: false,
  },
  {
    id: "week3-002",
    titleFa: "آسیب از ارتفاع بالا",
    titleEn: "Damage Opponents from High Ground",
    descriptionFa: "از ارتفاع بالا به دشمنان آسیب بزنید",
    category: "weekly",
    xpReward: 20000,
    target: 300,
    targetUnit: "آسیب",
    week: 3,
    season: "chapter7-season2",
    tags: ["combat", "highground", "damage"],
    isNew: false,
  },
  {
    id: "week3-003",
    titleFa: "حذف در Crescent Cove",
    titleEn: "Eliminate Players at Crescent Cove",
    descriptionFa: "بازیکنان را در Crescent Cove حذف کنید",
    category: "weekly",
    xpReward: 20000,
    target: 3,
    targetUnit: "حذف",
    week: 3,
    season: "chapter7-season2",
    tags: ["combat", "eliminate", "location"],
    isNew: false,
  },
  {
    id: "week3-004",
    titleFa: "ساختن سازه",
    titleEn: "Build Structures",
    descriptionFa: "سازه‌های مختلف بسازید",
    category: "weekly",
    xpReward: 20000,
    target: 50,
    targetUnit: "سازه",
    week: 3,
    season: "chapter7-season2",
    tags: ["building", "structures"],
    isNew: false,
  },
  {
    id: "week3-005",
    titleFa: "بازماندن در طوفان",
    titleEn: "Outlast Opponents in Storm",
    descriptionFa: "در طوفان از دشمنان بیشتر دوام بیاورید",
    category: "weekly",
    xpReward: 20000,
    target: 200,
    targetUnit: "بازیکن",
    week: 3,
    season: "chapter7-season2",
    tags: ["survival", "storm"],
    isNew: false,
  },

  // WEEK 4
  {
    id: "week4-001",
    titleFa: "جمع‌آوری آیتم از Supply Drop",
    titleEn: "Collect Items from Supply Drops",
    descriptionFa: "آیتم‌ها را از Supply Drop‌ها جمع‌آوری کنید",
    category: "weekly",
    xpReward: 20000,
    target: 2,
    targetUnit: "Supply Drop",
    week: 4,
    season: "chapter7-season2",
    tags: ["looting", "supply"],
    isNew: false,
  },
  {
    id: "week4-002",
    titleFa: "آسیب با سلاح انفجاری",
    titleEn: "Deal Damage with Explosives",
    descriptionFa: "با سلاح‌های انفجاری به دشمنان آسیب بزنید",
    category: "weekly",
    xpReward: 20000,
    target: 300,
    targetUnit: "آسیب",
    week: 4,
    season: "chapter7-season2",
    tags: ["combat", "explosive", "damage"],
    isNew: false,
  },
  {
    id: "week4-003",
    titleFa: "حذف با تفنگ تک‌تیرانداز",
    titleEn: "Eliminate Players with Sniper Rifles",
    descriptionFa: "بازیکنان را با تفنگ تک‌تیراندازی حذف کنید",
    category: "weekly",
    xpReward: 20000,
    target: 2,
    targetUnit: "حذف",
    week: 4,
    season: "chapter7-season2",
    tags: ["combat", "sniper", "eliminate"],
    isNew: false,
  },
  {
    id: "week4-004",
    titleFa: "احیا در مکان‌های خاص",
    titleEn: "Revive Teammates at Specific Locations",
    descriptionFa: "همتیمی‌ها را در مکان‌های مشخص احیا کنید",
    category: "weekly",
    xpReward: 20000,
    target: 3,
    targetUnit: "احیا",
    week: 4,
    season: "chapter7-season2",
    tags: ["teamwork", "revive", "location"],
    isNew: false,
  },
  {
    id: "week4-005",
    titleFa: "باز کردن گاوصندوق",
    titleEn: "Open Vaults",
    descriptionFa: "گاوصندوق‌ها را باز کنید",
    category: "weekly",
    xpReward: 20000,
    target: 1,
    targetUnit: "گاوصندوق",
    week: 4,
    season: "chapter7-season2",
    tags: ["looting", "vault"],
    isNew: false,
  },

  // WEEK 5
  {
    id: "week5-001",
    titleFa: "باز کردن صندوق در Fossil Falls",
    titleEn: "Search Chests at Fossil Falls",
    descriptionFa: "صندوق‌ها را در Fossil Falls جستجو کنید",
    category: "weekly",
    xpReward: 20000,
    target: 5,
    targetUnit: "صندوق",
    week: 5,
    season: "chapter7-season2",
    tags: ["looting", "chests", "location"],
    isNew: false,
  },
  {
    id: "week5-002",
    titleFa: "آسیب با تفنگ تهاجمی",
    titleEn: "Damage Opponents with Assault Rifles",
    descriptionFa: "با تفنگ تهاجمی به دشمنان آسیب بزنید",
    category: "weekly",
    xpReward: 20000,
    target: 1000,
    targetUnit: "آسیب",
    week: 5,
    season: "chapter7-season2",
    tags: ["combat", "rifle", "damage"],
    isNew: false,
  },
  {
    id: "week5-003",
    titleFa: "حذف در Painted Palms",
    titleEn: "Eliminate Players at Painted Palms",
    descriptionFa: "بازیکنان را در Painted Palms حذف کنید",
    category: "weekly",
    xpReward: 20000,
    target: 3,
    targetUnit: "حذف",
    week: 5,
    season: "chapter7-season2",
    tags: ["combat", "eliminate", "location"],
    isNew: false,
  },
  {
    id: "week5-004",
    titleFa: "جمع‌آوری Slurp Juice",
    titleEn: "Collect Slurp Juice",
    descriptionFa: "Slurp Juice را جمع‌آوری کنید",
    category: "weekly",
    xpReward: 20000,
    target: 3,
    targetUnit: "محلول",
    week: 5,
    season: "chapter7-season2",
    tags: ["healing", "slurp"],
    isNew: false,
  },
  {
    id: "week5-005",
    titleFa: "تخریب وسایل نقلیه",
    titleEn: "Destroy Vehicles",
    descriptionFa: "وسایل نقلیه را تخریب کنید",
    category: "weekly",
    xpReward: 20000,
    target: 5,
    targetUnit: "وسیله",
    week: 5,
    season: "chapter7-season2",
    tags: ["vehicles", "destroy"],
    isNew: false,
  },

  // WEEK 6
  {
    id: "week6-001",
    titleFa: "حذف در Masked Meadows",
    titleEn: "Eliminate Opponents at Masked Meadows",
    descriptionFa: "دشمنان را در Masked Meadows حذف کنید",
    category: "weekly",
    xpReward: 20000,
    target: 3,
    targetUnit: "حذف",
    week: 6,
    season: "chapter7-season2",
    tags: ["combat", "eliminate", "location"],
    isNew: false,
  },
  {
    id: "week6-002",
    titleFa: "آسیب با سلاح سرد",
    titleEn: "Deal Melee Weapon Damage",
    descriptionFa: "با سلاح‌های سرد به دشمنان آسیب بزنید",
    category: "weekly",
    xpReward: 20000,
    target: 200,
    targetUnit: "آسیب",
    week: 6,
    season: "chapter7-season2",
    tags: ["combat", "melee", "damage"],
    isNew: false,
  },
  {
    id: "week6-003",
    titleFa: "باز کردن جعبه مهمات در Crescent Cove",
    titleEn: "Open Ammo Boxes at Crescent Cove",
    descriptionFa: "جعبه‌های مهمات را در Crescent Cove باز کنید",
    category: "weekly",
    xpReward: 20000,
    target: 5,
    targetUnit: "جعبه",
    week: 6,
    season: "chapter7-season2",
    tags: ["looting", "ammo", "location"],
    isNew: false,
  },
  {
    id: "week6-004",
    titleFa: "جمع‌آوری ماهی",
    titleEn: "Collect Fish",
    descriptionFa: "ماهی‌ها را از منابع آب جمع‌آوری کنید",
    category: "weekly",
    xpReward: 20000,
    target: 3,
    targetUnit: "ماهی",
    week: 6,
    season: "chapter7-season2",
    tags: ["fishing", "collect"],
    isNew: false,
  },
  {
    id: "week6-005",
    titleFa: "آسیب از پشت دیوار",
    titleEn: "Damage Opponents Through Walls",
    descriptionFa: "از پشت دیوار به دشمنان آسیب بزنید",
    category: "weekly",
    xpReward: 20000,
    target: 200,
    targetUnit: "آسیب",
    week: 6,
    season: "chapter7-season2",
    tags: ["combat", "damage", "wall"],
    isNew: false,
  },

  // WEEK 7
  {
    id: "week7-001",
    titleFa: "جمع‌آوری مکعب‌های آشوب در Polar Peak",
    titleEn: "Collect Chaos Cubes at Polar Peak",
    descriptionFa: "مکعب‌های آشوب را در Polar Peak جمع‌آوری کنید",
    category: "weekly",
    xpReward: 20000,
    target: 5,
    targetUnit: "مکعب",
    week: 7,
    season: "chapter7-season2",
    tags: ["collect", "chaos", "location"],
    isNew: false,
  },
  {
    id: "week7-002",
    titleFa: "حذف با شاتگان در مکان‌های نام‌دار",
    titleEn: "Eliminate Opponents Using Shotguns at Named Locations",
    descriptionFa: "دشمنان را با شاتگان در مکان‌های نام‌دار حذف کنید",
    category: "weekly",
    xpReward: 20000,
    target: 3,
    targetUnit: "حذف",
    week: 7,
    season: "chapter7-season2",
    tags: ["combat", "shotgun", "location"],
    isNew: false,
  },
  {
    id: "week7-003",
    titleFa: "آسیب به وسایل نقلیه با تفنگ تهاجمی",
    titleEn: "Deal Assault Rifle Damage to Vehicles",
    descriptionFa: "با تفنگ تهاجمی به وسایل نقلیه آسیب بزنید",
    category: "weekly",
    xpReward: 20000,
    target: 500,
    targetUnit: "آسیب",
    week: 7,
    season: "chapter7-season2",
    tags: ["combat", "rifle", "vehicles"],
    isNew: false,
  },
  {
    id: "week7-004",
    titleFa: "باز کردن صندوق‌های شناور",
    titleEn: "Search Floating Chests",
    descriptionFa: "صندوق‌های شناور را باز کنید",
    category: "weekly",
    xpReward: 20000,
    target: 3,
    targetUnit: "صندوق",
    week: 7,
    season: "chapter7-season2",
    tags: ["looting", "chests"],
    isNew: false,
  },
  {
    id: "week7-005",
    titleFa: "بازماندن در دایره‌های نهایی",
    titleEn: "Outlast Opponents in Final Circles",
    descriptionFa: "در دایره‌های نهایی از دشمنان بیشتر دوام بیاورید",
    category: "weekly",
    xpReward: 20000,
    target: 3,
    targetUnit: "بار",
    week: 7,
    season: "chapter7-season2",
    tags: ["survival", "endgame"],
    isNew: false,
  },

  // WEEK 8
  {
    id: "week8-001",
    titleFa: "آسیب به یادبود Ice King",
    titleEn: "Deal Damage to the Ice King's Monument",
    descriptionFa: "به یادبود Ice King آسیب بزنید",
    category: "weekly",
    xpReward: 20000,
    target: 500,
    targetUnit: "آسیب",
    week: 8,
    season: "chapter7-season2",
    tags: ["combat", "damage", "monument"],
    isNew: true,
  },
  {
    id: "week8-002",
    titleFa: "جمع‌آوری قطعات Ice King",
    titleEn: "Collect Ice King Fragments",
    descriptionFa: "قطعات Ice King را جمع‌آوری کنید",
    category: "weekly",
    xpReward: 20000,
    target: 5,
    targetUnit: "قطعه",
    week: 8,
    season: "chapter7-season2",
    tags: ["collect", "iceking"],
    isNew: true,
  },
  {
    id: "week8-003",
    titleFa: "حذف پیروان Dark Voyager",
    titleEn: "Eliminate Dark Voyager Disciples",
    descriptionFa: "پیروان Dark Voyager را حذف کنید",
    category: "weekly",
    xpReward: 20000,
    target: 5,
    targetUnit: "حذف",
    week: 8,
    season: "chapter7-season2",
    tags: ["combat", "boss", "eliminate"],
    isNew: true,
  },
  {
    id: "week8-004",
    titleFa: "باز کردن گاوصندوق نزدیک سازه‌های یخی",
    titleEn: "Open Vaults near Ice Structures",
    descriptionFa: "گاوصندوق‌ها را نزدیک سازه‌های یخی باز کنید",
    category: "weekly",
    xpReward: 20000,
    target: 1,
    targetUnit: "گاوصندوق",
    week: 8,
    season: "chapter7-season2",
    tags: ["looting", "vault", "location"],
    isNew: true,
  },
  {
    id: "week8-005",
    titleFa: "احیا در قلمرو یخ",
    titleEn: "Revive Teammates in the Ice Kingdom",
    descriptionFa: "همتیمی‌ها را در قلمرو یخ احیا کنید",
    category: "weekly",
    xpReward: 20000,
    target: 2,
    targetUnit: "احیا",
    week: 8,
    season: "chapter7-season2",
    tags: ["teamwork", "revive", "location"],
    isNew: true,
  },

  // ===== STORY QUESTS - PATH OF THE VOYAGER =====
  {
    id: "story-001",
    titleFa: "پیدا کردن سیگنال Dark Voyager",
    titleEn: "Find the Dark Voyager's Signal at Crescent Cove",
    descriptionFa: "سیگنال Dark Voyager را در Crescent Cove پیدا کنید",
    category: "story",
    xpReward: 15000,
    target: 1,
    targetUnit: "سیگنال",
    season: "chapter7-season2",
    tags: ["story", "exploration", "location"],
  },
  {
    id: "story-002",
    titleFa: "جمع‌آوری مکعب‌های آشوب برای ردیابی فساد",
    titleEn: "Collect Chaos Cubes to Track the Corruption",
    descriptionFa: "مکعب‌های آشوب را برای ردیابی فساد جمع‌آوری کنید",
    category: "story",
    xpReward: 15000,
    target: 10,
    targetUnit: "مکعب",
    season: "chapter7-season2",
    tags: ["story", "collect", "chaos"],
  },
  {
    id: "story-003",
    titleFa: "تخریب گیرنده‌های مکعب آشوب",
    titleEn: "Destroy Chaos Cube Emitters",
    descriptionFa: "گیرنده‌های مکعب آشوب را تخریب کنید",
    category: "story",
    xpReward: 15000,
    target: 3,
    targetUnit: "گیرنده",
    season: "chapter7-season2",
    tags: ["story", "destroy", "chaos"],
  },
  {
    id: "story-004",
    titleFa: "کشف پایگاه مخفی Dark Voyager",
    titleEn: "Discover the Dark Voyager's Hidden Base",
    descriptionFa: "پایگاه مخفی Dark Voyager را کشف کنید",
    category: "story",
    xpReward: 20000,
    target: 1,
    targetUnit: "پایگاه",
    season: "chapter7-season2",
    tags: ["story", "exploration"],
  },
  {
    id: "story-005",
    titleFa: "شکست دادن Dark Voyager",
    titleEn: "Defeat the Dark Voyager",
    descriptionFa: "Dark Voyager را در نبرد نهایی شکست دهید",
    category: "story",
    xpReward: 40000,
    target: 1,
    targetUnit: "شکست",
    season: "chapter7-season2",
    tags: ["story", "boss", "finale"],
  },
  {
    id: "story-006",
    titleFa: "تحقیق در مکان‌های مشکوک",
    titleEn: "Investigate Suspicious Locations",
    descriptionFa: "مکان‌های مشکوک را در سراسر نقشه بررسی کنید",
    category: "story",
    xpReward: 10000,
    target: 4,
    targetUnit: "مکان",
    season: "chapter7-season2",
    tags: ["story", "exploration"],
  },
  {
    id: "story-007",
    titleFa: "جمع‌آوری ۷۰ مکعب آشوب",
    titleEn: "Collect 70 Chaos Cubes Total",
    descriptionFa: "در مجموع ۷۰ مکعب آشوب را در طول فصل جمع‌آوری کنید",
    category: "story",
    xpReward: 80000,
    target: 70,
    targetUnit: "مکعب",
    season: "chapter7-season2",
    tags: ["story", "collect", "milestone"],
  },

  // ===== BATTLE PASS QUESTS =====
  {
    id: "bp-foundation-001",
    titleFa: "آسیب با سلاح Foundation",
    titleEn: "Deal Damage with Foundation's Weapons",
    descriptionFa: "با سلاح‌های خاص Foundation آسیب بزنید",
    category: "battlepass",
    xpReward: 10000,
    target: 500,
    targetUnit: "آسیب",
    season: "chapter7-season2",
    tags: ["battlepass", "foundation", "damage"],
  },
  {
    id: "bp-foundation-002",
    titleFa: "حذف با Foundation",
    titleEn: "Eliminate Opponents with Foundation",
    descriptionFa: "دشمنان را با Foundation حذف کنید",
    category: "battlepass",
    xpReward: 10000,
    target: 3,
    targetUnit: "حذف",
    season: "chapter7-season2",
    tags: ["battlepass", "foundation", "eliminate"],
  },
  {
    id: "bp-foundation-003",
    titleFa: "تکمیل بازی‌ها با Foundation",
    titleEn: "Complete Matches as Foundation",
    descriptionFa: "با اسکین Foundation بازی‌ها را تکمیل کنید",
    category: "battlepass",
    xpReward: 10000,
    target: 5,
    targetUnit: "بازی",
    season: "chapter7-season2",
    tags: ["battlepass", "foundation"],
  },
  {
    id: "bp-iceking-001",
    titleFa: "جمع‌آوری قطعات Ice King",
    titleEn: "Collect Ice King Fragments",
    descriptionFa: "قطعات Ice King را برای قدرت بیشتر جمع‌آوری کنید",
    category: "battlepass",
    xpReward: 10000,
    target: 5,
    targetUnit: "قطعه",
    season: "chapter7-season2",
    tags: ["battlepass", "iceking", "collect"],
  },
  {
    id: "bp-iceking-002",
    titleFa: "آسیب در مناطق یخی",
    titleEn: "Deal Damage in Ice Zones",
    descriptionFa: "در مناطق یخی به دشمنان آسیب بزنید",
    category: "battlepass",
    xpReward: 10000,
    target: 500,
    targetUnit: "آسیب",
    season: "chapter7-season2",
    tags: ["battlepass", "iceking", "damage", "location"],
  },
  {
    id: "bp-jules-001",
    titleFa: "هک کردن دستگاه‌های دشمن",
    titleEn: "Hack Enemy Devices",
    descriptionFa: "دستگاه‌های دشمن را هک کنید",
    category: "battlepass",
    xpReward: 10000,
    target: 3,
    targetUnit: "هک",
    season: "chapter7-season2",
    tags: ["battlepass", "jules", "hack"],
  },
  {
    id: "bp-jules-002",
    titleFa: "حذف با آسیب دام",
    titleEn: "Eliminate Opponents with Trap Damage",
    descriptionFa: "دشمنان را با آسیب دام حذف کنید",
    category: "battlepass",
    xpReward: 10000,
    target: 3,
    targetUnit: "حذف",
    season: "chapter7-season2",
    tags: ["battlepass", "jules", "trap"],
  },

  // ===== RANKED QUESTS =====
  {
    id: "ranked-001",
    titleFa: "رسیدن به رتبه برنز",
    titleEn: "Reach Bronze Rank",
    descriptionFa: "در حالت رنک‌دار به رتبه برنز برسید",
    category: "ranked",
    xpReward: 5000,
    target: 1,
    targetUnit: "رتبه",
    season: "chapter7-season2",
    tags: ["ranked", "rank"],
  },
  {
    id: "ranked-002",
    titleFa: "رسیدن به رتبه نقره",
    titleEn: "Reach Silver Rank",
    descriptionFa: "در حالت رنک‌دار به رتبه نقره برسید",
    category: "ranked",
    xpReward: 5000,
    target: 1,
    targetUnit: "رتبه",
    season: "chapter7-season2",
    tags: ["ranked", "rank"],
  },
  {
    id: "ranked-003",
    titleFa: "رسیدن به رتبه طلا",
    titleEn: "Reach Gold Rank",
    descriptionFa: "در حالت رنک‌دار به رتبه طلا برسید",
    category: "ranked",
    xpReward: 5000,
    target: 1,
    targetUnit: "رتبه",
    season: "chapter7-season2",
    tags: ["ranked", "rank"],
  },
  {
    id: "ranked-004",
    titleFa: "رسیدن به رتبه پلاتین",
    titleEn: "Reach Platinum Rank",
    descriptionFa: "در حالت رنک‌دار به رتبه پلاتین برسید",
    category: "ranked",
    xpReward: 5000,
    target: 1,
    targetUnit: "رتبه",
    season: "chapter7-season2",
    tags: ["ranked", "rank"],
  },
  {
    id: "ranked-005",
    titleFa: "رسیدن به رتبه الماس",
    titleEn: "Reach Diamond Rank",
    descriptionFa: "در حالت رنک‌دار به رتبه الماس برسید",
    category: "ranked",
    xpReward: 5000,
    target: 1,
    targetUnit: "رتبه",
    season: "chapter7-season2",
    tags: ["ranked", "rank"],
  },
  {
    id: "ranked-006",
    titleFa: "رسیدن به رتبه الیت",
    titleEn: "Reach Elite Rank",
    descriptionFa: "در حالت رنک‌دار به رتبه الیت برسید",
    category: "ranked",
    xpReward: 5000,
    target: 1,
    targetUnit: "رتبه",
    season: "chapter7-season2",
    tags: ["ranked", "rank"],
  },
  {
    id: "ranked-007",
    titleFa: "رسیدن به رتبه چمپیون",
    titleEn: "Reach Champion Rank",
    descriptionFa: "در حالت رنک‌دار به رتبه چمپیون برسید",
    category: "ranked",
    xpReward: 5000,
    target: 1,
    targetUnit: "رتبه",
    season: "chapter7-season2",
    tags: ["ranked", "rank"],
  },
  {
    id: "ranked-008",
    titleFa: "برنده شدن در حالت رنک‌دار",
    titleEn: "Win a Ranked Match",
    descriptionFa: "یک بازی در حالت رنک‌دار ببرید",
    category: "ranked",
    xpReward: 10000,
    target: 1,
    targetUnit: "برد",
    season: "chapter7-season2",
    tags: ["ranked", "win"],
  },
  {
    id: "ranked-009",
    titleFa: "آسیب در حالت رنک‌دار",
    titleEn: "Deal Damage in Ranked",
    descriptionFa: "در حالت رنک‌دار به دشمنان آسیب بزنید",
    category: "ranked",
    xpReward: 5000,
    target: 5000,
    targetUnit: "آسیب",
    season: "chapter7-season2",
    tags: ["ranked", "damage"],
  },
  {
    id: "ranked-010",
    titleFa: "پایان در ۱۰ نفر اول",
    titleEn: "Complete Top 10 in Ranked",
    descriptionFa: "در حالت رنک‌دار در ۱۰ نفر اول به پایان برسید",
    category: "ranked",
    xpReward: 5000,
    target: 3,
    targetUnit: "بار",
    season: "chapter7-season2",
    tags: ["ranked", "placement"],
  },

  // ===== STAR WARS EVENT QUESTS =====
  {
    id: "sw-galactic-001",
    titleFa: "شکست Stormtrooper‌های امپراتوری",
    titleEn: "Defeat Imperial Stormtroopers",
    descriptionFa: "Stormtrooper‌های امپراتوری را در نقشه Galactic Siege شکست دهید",
    category: "event",
    xpReward: 10000,
    target: 20,
    targetUnit: "حذف",
    season: "chapter7-season2",
    tags: ["starwars", "event", "eliminate"],
    isNew: true,
  },
  {
    id: "sw-galactic-002",
    titleFa: "جمع‌آوری کریستال‌های Kyber",
    titleEn: "Collect Kyber Crystals",
    descriptionFa: "کریستال‌های Kyber را در نقشه Galactic Siege جمع‌آوری کنید",
    category: "event",
    xpReward: 10000,
    target: 5,
    targetUnit: "کریستال",
    season: "chapter7-season2",
    tags: ["starwars", "event", "collect"],
    isNew: true,
  },
  {
    id: "sw-galactic-003",
    titleFa: "استفاده از نیروی فورس",
    titleEn: "Use Force Powers",
    descriptionFa: "قدرت‌های فورس را در نقشه Galactic Siege استفاده کنید",
    category: "event",
    xpReward: 10000,
    target: 10,
    targetUnit: "بار",
    season: "chapter7-season2",
    tags: ["starwars", "event", "force"],
    isNew: true,
  },
  {
    id: "sw-galactic-004",
    titleFa: "تکمیل مأموریت Galactic Siege",
    titleEn: "Complete the Galactic Siege Mission",
    descriptionFa: "مأموریت Galactic Siege را با موفقیت تکمیل کنید",
    category: "event",
    xpReward: 10000,
    target: 1,
    targetUnit: "مأموریت",
    season: "chapter7-season2",
    tags: ["starwars", "event", "complete"],
    isNew: true,
  },
  {
    id: "sw-vader-001",
    titleFa: "فرار از شناسایی Vader",
    titleEn: "Avoid Vader's Detection",
    descriptionFa: "از شناسایی توسط Vader در نقشه Escape Vader اجتناب کنید",
    category: "event",
    xpReward: 10000,
    target: 1,
    targetUnit: "فرار",
    season: "chapter7-season2",
    tags: ["starwars", "event", "escape"],
    isNew: true,
  },
  {
    id: "sw-vader-002",
    titleFa: "جمع‌آوری اطلاعات شورشیان",
    titleEn: "Collect Rebel Intel",
    descriptionFa: "اطلاعات شورشیان را در نقشه Escape Vader جمع‌آوری کنید",
    category: "event",
    xpReward: 10000,
    target: 5,
    targetUnit: "اطلاعات",
    season: "chapter7-season2",
    tags: ["starwars", "event", "collect"],
    isNew: true,
  },
  {
    id: "sw-droid-001",
    titleFa: "ساخت دروید",
    titleEn: "Build Droids",
    descriptionFa: "دروید بسازید در نقشه Droid Tycoon",
    category: "event",
    xpReward: 10000,
    target: 10,
    targetUnit: "دروید",
    season: "chapter7-season2",
    tags: ["starwars", "event", "build"],
    isNew: true,
  },
  {
    id: "sw-droid-002",
    titleFa: "کسب اعتبار در Droid Tycoon",
    titleEn: "Earn Credits in Droid Tycoon",
    descriptionFa: "اعتبار کسب کنید در نقشه Droid Tycoon",
    category: "event",
    xpReward: 10000,
    target: 1000,
    targetUnit: "اعتبار",
    season: "chapter7-season2",
    tags: ["starwars", "event", "credits"],
    isNew: true,
  },

  // ===== MILESTONE QUESTS =====
  {
    id: "milestone-001",
    titleFa: "اولین برد",
    titleEn: "First Victory Royale",
    descriptionFa: "اولین Victory Royale خود را بدست آورید",
    category: "milestone",
    xpReward: 10000,
    target: 1,
    targetUnit: "برد",
    season: "chapter7-season2",
    tags: ["milestone", "win"],
  },
  {
    id: "milestone-002",
    titleFa: "۵ Victory Royale",
    titleEn: "Achieve 5 Victory Royales",
    descriptionFa: "۵ Victory Royale بدست آورید",
    category: "milestone",
    xpReward: 20000,
    target: 5,
    targetUnit: "برد",
    season: "chapter7-season2",
    tags: ["milestone", "win"],
  },
  {
    id: "milestone-003",
    titleFa: "۱۰ Victory Royale",
    titleEn: "Achieve 10 Victory Royales",
    descriptionFa: "۱۰ Victory Royale بدست آورید",
    category: "milestone",
    xpReward: 30000,
    target: 10,
    targetUnit: "برد",
    season: "chapter7-season2",
    tags: ["milestone", "win"],
  },
  {
    id: "milestone-004",
    titleFa: "۱۰۰ حذف در فصل",
    titleEn: "100 Eliminations in Season",
    descriptionFa: "در طول فصل ۱۰۰ دشمن را حذف کنید",
    category: "milestone",
    xpReward: 20000,
    target: 100,
    targetUnit: "حذف",
    season: "chapter7-season2",
    tags: ["milestone", "eliminate"],
  },
  {
    id: "milestone-005",
    titleFa: "۵۰۰ صندوق باز شده",
    titleEn: "Open 500 Chests in Season",
    descriptionFa: "در طول فصل ۵۰۰ صندوق باز کنید",
    category: "milestone",
    xpReward: 15000,
    target: 500,
    targetUnit: "صندوق",
    season: "chapter7-season2",
    tags: ["milestone", "looting"],
  },
  {
    id: "milestone-006",
    titleFa: "رسیدن به سطح ۱۰۰ Battle Pass",
    titleEn: "Reach Level 100 Battle Pass",
    descriptionFa: "Battle Pass را به سطح ۱۰۰ برسانید",
    category: "milestone",
    xpReward: 50000,
    target: 100,
    targetUnit: "سطح",
    season: "chapter7-season2",
    tags: ["milestone", "battlepass"],
  },
  {
    id: "milestone-007",
    titleFa: "شرکت در ۵۰ بازی",
    titleEn: "Play 50 Matches",
    descriptionFa: "در ۵۰ بازی شرکت کنید",
    category: "milestone",
    xpReward: 10000,
    target: 50,
    targetUnit: "بازی",
    season: "chapter7-season2",
    tags: ["milestone", "participation"],
  },
];

export const QUEST_CATEGORIES = {
  daily: { labelFa: "روزانه", labelEn: "Daily", color: "#22c55e", icon: "☀️" },
  weekly: { labelFa: "هفتگی", labelEn: "Weekly", color: "#3b82f6", icon: "📅" },
  story: { labelFa: "داستانی", labelEn: "Story", color: "#f59e0b", icon: "📖" },
  battlepass: { labelFa: "پس رزمی", labelEn: "Battle Pass", color: "#8b5cf6", icon: "🏆" },
  ranked: { labelFa: "رنک‌دار", labelEn: "Ranked", color: "#ef4444", icon: "🎯" },
  event: { labelFa: "رویداد", labelEn: "Event", color: "#06b6d4", icon: "⭐" },
  milestone: { labelFa: "نقطه عطف", labelEn: "Milestone", color: "#f97316", icon: "🎖️" },
};
